name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: test-env

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-playwright python-dotenv allure-pytest
        
    - name: Install Playwright Browsers
      run: playwright install --with-deps
      
    - name: Run Pytest with Allure
      env:
        # These map directly to the GitHub Settings -> Secrets
        BASE_URL: ${{ secrets.BASE_URL }}
        STANDARD_USER: ${{ secrets.STANDARD_USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: pytest tests/ --alluredir=allure-results
      
    - name: Upload Allure Results Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
        retention-days: 7